### ISSUE TITLE
Plugin no responding.

### ISSUE THREAD

**Issue by yedemon** [klesun/deep-assoc-completion-vscode#8]
After install. I wrote code like 

$aa=['a'=>1];

$a = $aa['....

However i got nothing. 

I tried to follow the "Steps to run", however what does 'hit F5 to run sandbox instance of vscode' mean? F5 is debug mode right?

**Comment by klesun** [comment]
Hi. The plugin stopped working in some version of vscode sadly, see https://github.com/klesun/deep-assoc-completion-vscode/issues/7

Need a PR to fix that.

**Comment by yedemon** [comment]
Thanks for reply. I've read that issue, and I don't think I have reached that far. I am confused with "Steps to run". How should I get this plugin running? What's the sandbox of vscode? Can't find it anywhere.

**Comment by klesun** [comment]
You can't get this plugin running, it does not work in any recent version of vscode.

**Comment by yedemon** [comment]
Ok.`` I see. I will try a earlier version of Vscode later. And see if i could make a pr.. Thanks again..

**Comment by klesun** [comment]
Seems to work in vscode [v1.52](https://code.visualstudio.com/updates/v1_52) at least

![image](https://user-images.githubusercontent.com/5202330/158956519-fab0b296-68eb-4d14-80b0-3ce7e4fcef3a.png)

On [v1.53](https://code.visualstudio.com/updates/v1_53) it did not work already

**Comment by ging-dev** [comment]
> Seems to work in vscode [v1.44](https://code.visualstudio.com/updates/v1_44) at least
> 
> ![image](https://user-images.githubusercontent.com/5202330/158956519-fab0b296-68eb-4d14-80b0-3ce7e4fcef3a.png)

it seems `require()` in `main.js` no longer works, I tried `tsc -p ./` to compile typescript to es6 js and it seems to work again. I have tried to do the same thing on the `language server` package but without success.

**Comment by klesun** [comment]
Damn, this whole time all I had to do was just to remove `type:"module"` from `package.json`... Will compose a patch soon. Thank you very much for the insight!

**Comment by klesun** [comment]
Released a fix: `v0.8.1`

It now works in the latest vscode!

![image](https://user-images.githubusercontent.com/5202330/159175767-05e977a8-265a-47aa-aaeb-ff4e12142720.png)

**Comment by yedemon** [comment]
Oh`` it really works! Love you so much.
